/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.procesadortexto;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.font.TextAttribute.FONT;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author josed
 */
public class Notepad extends javax.swing.JFrame {
    
    //Font fuente = new Font("Arial", 0, 12);
    private Integer size = 0;
    private String fuenteNueva = "";
    
    /**
     * Creates new form Notepad
     */
    public Notepad() {
        initComponents();
        //jTextArea1.setFont(fuente);
        DateTimeFormatter formateador = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
        Runnable runnable = new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(500);
                        lblFecha.setText(formateador.format(LocalDateTime.now()));
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        };
        Thread hilo = new Thread(runnable);
        hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jOptionPane1 = new javax.swing.JOptionPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        lblLongitud = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lblFecha = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        lblUbicacion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuFuente = new javax.swing.JMenu();
        menuColor = new javax.swing.JMenuItem();
        menuFuente = new javax.swing.JMenuItem();
        jMenuTamaño = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(401, 25));
        jPanel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPanel2KeyTyped(evt);
            }
        });
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setMinimumSize(new java.awt.Dimension(170, 0));
        jLabel3.setPreferredSize(new java.awt.Dimension(170, 0));
        jPanel2.add(jLabel3);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setBorder(new javax.swing.border.MatteBorder(null));
        jSeparator3.setPreferredSize(new java.awt.Dimension(4, 20));
        jPanel2.add(jSeparator3);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Tamaño:");
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 16));
        jLabel1.setMinimumSize(new java.awt.Dimension(50, 16));
        jLabel1.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel2.add(jLabel1);

        lblLongitud.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLongitud.setMinimumSize(new java.awt.Dimension(70, 16));
        lblLongitud.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel2.add(lblLongitud);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setBorder(new javax.swing.border.MatteBorder(null));
        jSeparator4.setPreferredSize(new java.awt.Dimension(4, 20));
        jPanel2.add(jSeparator4);

        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setMinimumSize(new java.awt.Dimension(90, 16));
        lblFecha.setPreferredSize(new java.awt.Dimension(130, 16));
        jPanel2.add(lblFecha);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setBorder(new javax.swing.border.MatteBorder(null));
        jSeparator5.setPreferredSize(new java.awt.Dimension(4, 20));
        jPanel2.add(jSeparator5);

        jLabel2.setText("Ubicación ");
        jPanel2.add(jLabel2);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setBorder(new javax.swing.border.MatteBorder(null));
        jSeparator6.setPreferredSize(new java.awt.Dimension(4, 20));
        jPanel2.add(jSeparator6);

        lblUbicacion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUbicacion.setMinimumSize(new java.awt.Dimension(100, 16));
        lblUbicacion.setPreferredSize(new java.awt.Dimension(250, 16));
        jPanel2.add(lblUbicacion);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenuFuente.setText("Formato");
        jMenuFuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFuenteActionPerformed(evt);
            }
        });

        menuColor.setText("Color");
        menuColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuColorActionPerformed(evt);
            }
        });
        jMenuFuente.add(menuColor);

        menuFuente.setText("Fuente");
        menuFuente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFuenteActionPerformed(evt);
            }
        });
        jMenuFuente.add(menuFuente);

        jMenuTamaño.setText("Tamaño");
        jMenuTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTamañoActionPerformed(evt);
            }
        });
        jMenuFuente.add(jMenuTamaño);

        jMenuBar1.add(jMenuFuente);

        jMenu3.setText("Ayuda");

        jMenuItem3.setText("Acerca del Bloc de Notas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
        jOptionPane1.showMessageDialog(null,"Desarrolado por:\n"+
                "Adolfo Salado Lopez y \nJose Luis Dommarco Berrocal");
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        int seleccion = jFileChooser1.showOpenDialog(jMenu1);

        File archivo = null;
        if (seleccion == 0){
            try {
                jTextArea1.setText("");
                BufferedReader reader = null;
                archivo = jFileChooser1.getSelectedFile();
                reader = new BufferedReader(new FileReader(archivo));
                String linea = reader.readLine();
                while(linea!=null){
                    jTextArea1.append(linea);
                    jTextArea1.append(System.getProperty("line.separator"));//hace un enter
                    linea = reader.readLine();
                }
                reader.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Notepad.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Notepad.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        lblLongitud.setText(Integer.toString(jTextArea1.getText().length()));
        String ubicacion = archivo.getAbsolutePath();
        lblUbicacion.setText(ubicacion);
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        
        int seleccion = jFileChooser1.showSaveDialog(jTextArea1);
        if(seleccion == 0){
            try {
                PrintWriter writer = null;
                File archivo = jFileChooser1.getSelectedFile();
                writer = new PrintWriter(archivo);
                writer.print(jTextArea1.getText());
                writer.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Notepad.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuColorActionPerformed
        JColorChooser colores = new JColorChooser();
        var panelColor = new JPanel();
        panelColor.setLayout(new FlowLayout());
        
        colores.setSize(400, 400);
        colores.setVisible(true);

        var boton = new JButton();
        boton.setText("Aceptar");
        var frameColor = new JFrame();
        panelColor.add(colores);
        panelColor.add(boton);
        frameColor.add(panelColor);
        frameColor.setSize(500, 500);
       
        
         boton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Color color = colores.getColor();
                frameColor.setVisible(false);
                jTextArea1.setForeground(color);
                
            }
         });
         
          frameColor.setVisible(true);
        
    }//GEN-LAST:event_menuColorActionPerformed

    private void menuFuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFuenteActionPerformed
        var frameFuente = new JFrame();
        var panelFuente = new JPanel();
        var comboFuente = new JComboBox();
        var textoFuente = new JLabel();
        var boton = new JButton();
        
        /* Configuración del panel */
        panelFuente.setLayout(new FlowLayout());
        
        /* Configuración botón */
        boton.setText("Aceptar");
        
        /* Configuración Label */
        textoFuente.setText("Seleccione una fuente: ");
        
        /* Configuración Frame */
        frameFuente.setBounds(200, 200, 400, 100);
        
        /* Rellenar JComboBox */
        var fuentes = new ArrayList<String>();
        fuentes.add("Verdana");
        fuentes.add("Times New Roman");
        fuentes.add("Helvetica");
        
        for (String fuente : fuentes) {
            comboFuente.addItem(fuente);
        }
        
        panelFuente.add(textoFuente);
        panelFuente.add(comboFuente);
        panelFuente.add(boton);
        
        frameFuente.add(panelFuente);
        
         boton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                fuenteNueva = (String) comboFuente.getSelectedItem();
                frameFuente.setVisible(false);
                jTextArea1.setFont(new Font(fuenteNueva, Font.PLAIN, jTextArea1.getFont().getSize()));
            }
         });
        
        frameFuente.setVisible(true);
        
        
        
    }//GEN-LAST:event_menuFuenteActionPerformed

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        
        int contador = jTextArea1.getText().length();
        lblLongitud.setText(String.valueOf(contador));
        
    }//GEN-LAST:event_jTextArea1KeyTyped

    private void jPanel2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2KeyTyped

    private void jMenuFuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFuenteActionPerformed
        
        Font font = new Font("Fira Code",Font.PLAIN,12);
        jTextArea1.setFont(font);
        
    }//GEN-LAST:event_jMenuFuenteActionPerformed

    private void jMenuTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTamañoActionPerformed
        var frameFuente = new JFrame();
        var panelFuente = new JPanel();

        
        var tamaños = new ArrayList<Integer>();
        
        for (int i = 1; i <= 64; i*=2) {
            tamaños.add(i);
        }
        
        var comboBox = new JComboBox();

        for(Integer numero : tamaños) {
            comboBox.addItem(numero);
        }
        panelFuente.setLayout(new FlowLayout());
        
        var texto = new JLabel();
        
        var boton = new JButton();
        boton.setText("Aceptar");
        
        texto.setText("Seleccione el tamaño del texto: ");
        panelFuente.add(texto);
        panelFuente.add(comboBox);
        panelFuente.add(boton);
        frameFuente.add(panelFuente);
        frameFuente.setBounds(200, 200, 400, 100);
        
        Font fuentecita = jTextArea1.getFont();
        boton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                size = (Integer) comboBox.getSelectedItem();
                frameFuente.setVisible(false);
                jTextArea1.setFont(new Font(fuentecita.toString(), 0, size));
            }
         });


        frameFuente.setVisible(true);
    }//GEN-LAST:event_jMenuTamañoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notepad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notepad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFuente;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuTamaño;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblLongitud;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JMenuItem menuColor;
    private javax.swing.JMenuItem menuFuente;
    // End of variables declaration//GEN-END:variables
}
